dbt_tutorial:
  outputs:
    dev:
      catalog: dbt_tutorial_dev
      host: dbc-d9c88a5f-c6ff.cloud.databricks.com
      http_path: /sql/1.0/warehouses/c4119449bc7ea628
      schema: default
      threads: 1
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      type: databricks
  target: dev
